theme: jekyll-theme-midnight
title: Synthasmablogia
description: I'll write about tech and projects here sometimes
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
