XoarkSeries = Object.freeze({
    None:              "None",
    Hex:               "Color",
    Base64:            "Base64",
    P:                 "P()~()..8",
    Missing_Broken:    "Missing / Broken",
    Satellits:         "Satellits:",
    Praspis:           "Praspis,",
    Gnocchi:           "Gnocchi",
    Runtime:           "Runtime",
});

XoarkAlbumType = Object.freeze({
    Album:             "Album",
    EP:                "E.P.",
    Split:             "Split",
    VA:                "V.A.",
    Journey:           "Journey",
});

XoarkGenre = Object.freeze({
    IDM:               "IDM",
    Noise:             "Noise",
    Glitch:            "Glitch",
    Breakcore:         "Breakcore",
    SoCalledDnb:       "So-called DnB",
    Ambient:           "Ambient",
});

(() => {
    window.xoark_database = [
        {
            listened: "2026.08.02",
            released: "2024.06.29",
            title: "See2",
            art: "see 2.jpg",
            url: "https://suimoe.bandcamp.com/album/see2",
            genre: XoarkGenre.Breakcore,
            duration: "00:45:54",
            rating: 4,
            type: XoarkAlbumType.VA,
            favorite: "y?",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.02",
            released: "2024.02.11",
            title: "Chrolps / Nlockpyi",
            art: "chrolps / nlockpyi.jpg",
            url: "https://xoark.bandcamp.com/album/chrolps-nlockpyi",
            genre: XoarkGenre.Breakcore,
            duration: "00:11:44",
            rating: 2,
            type: XoarkAlbumType.EP,
            favorite: "",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.03",
            released: "2025.06.08",
            title: "Tiryclui",
            art: "tiryclui.jpg",
            url: "https://xoark.bandcamp.com/album/tiryclui",
            genre: XoarkGenre.IDM,
            duration: "01:23:33",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "02",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.03",
            released: "2026.05.30",
            title: "Parfait Retrieval",
            art: "parfait retrieval.jpg",
            url: "https://xoark.bandcamp.com/album/parfait-retrieval",
            genre: XoarkGenre.SoCalledDnB,
            duration: "01:12:50",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "Morphedfeather",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.04",
            released: "2025.12.29",
            title: "Tea Flange",
            art: "tea flange.jpg",
            url: "https://xoark.bandcamp.com/album/tea-flange",
            genre: XoarkGenre.SoCalledDnB,
            duration: "01:11:28",
            rating: 2,
            type: XoarkAlbumType.Album,
            favorite: "",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.04",
            released: "2024.11.27",
            title: "1sky",
            art: "1 sky.jpg",
            url: "https://lego6.bandcamp.com/album/1sky",
            genre: XoarkGenre.Breakcore,
            duration: "00:34:47",
            rating: 4,
            type: XoarkAlbumType.Split,
            favorite: "Pstch_n46",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.04",
            released: "2025.07.21",
            title: "Satellits: Descriptor",
            art: "satellits: descriptor.jpg",
            url: "https://xoark.bandcamp.com/album/satellits-descriptor",
            genre: XoarkGenre.IDM,
            duration: "01:27:14",
            rating: 3,
            type: XoarkAlbumType.Album,
            favorite: "Spacewire 02",
            listens: 1,
            series: XoarkSeries.Satellits,
        },
        {
            listened: "2026.08.04",
            released: "2025.07.25",
            title: "#92b1e4",
            art: "#92 b 1 e 4.jpg",
            url: "https://xoark.bandcamp.com/album/92b1e4",
            genre: XoarkGenre.IDM,
            duration: "00:35:32",
            rating: 1,
            type: XoarkAlbumType.Journey,
            favorite: "",
            listens: 1,
            series: XoarkSeries.Hex,
        },
        {
            listened: "2026.08.05",
            released: "2025.08.01",
            title: "Marble Bird Resistor",
            art: "marble bird resistor.jpg",
            url: "https://xoark.bandcamp.com/album/marble-bird-resistor-ep",
            genre: XoarkGenre.Breakcore,
            duration: "00:39:08",
            rating: 3,
            type: XoarkAlbumType.EP,
            favorite: "Submarine1",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.05",
            released: "2025.02.02",
            title: "Nssrwnt",
            art: "nssrwnt.jpg",
            url: "https://xoark.bandcamp.com/album/nssrwnt",
            genre: XoarkGenre.Ambient,
            duration: "01:09:30",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "Navscr",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.05",
            released: "2026.08.01",
            title: "Silkbuffer",
            art: "silkbuffer.jpg",
            url: "https://xoark.bandcamp.com/album/silkbuffer-ep",
            genre: XoarkGenre.Breakcore,
            duration: "00:35:45",
            rating: 3,
            type: XoarkAlbumType.EP,
            favorite: "",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.05",
            released: "2024.08.27",
            title: "nemnge",
            art: "nemnge.jpg",
            url: "https://xoark.bandcamp.com/album/nemnge",
            genre: XoarkGenre.Ambient,
            duration: "01:05:38",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "Nihsk",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.06",
            released: "2025.04.27",
            title: "Ice Aqautics",
            art: "ice aqautics.jpg",
            url: "https://xoark.bandcamp.com/album/ice-aqautics",
            genre: XoarkGenre.IDM,
            duration: "00:33:17",
            rating: 3,
            type: XoarkAlbumType.Journey,
            favorite: "",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.06",
            released: "2025.02.04",
            title: "Talprcrii",
            art: "talprcrii.jpg",
            url: "https://xoark.bandcamp.com/album/talprcrii",
            genre: XoarkGenre.IDM,
            duration: "00:53:31",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "01",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.06",
            released: "2025.07.06",
            title: "Extracted (-75699)",
            art: "extracted ( 75699).jpg",
            url: "https://xoark.bandcamp.com/album/extracted-75699",
            genre: XoarkGenre.IDM,
            duration: "01:04:33",
            rating: 2,
            type: XoarkAlbumType.Album,
            favorite: "44428",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.06",
            released: "2025.01.16",
            title: "2 tracks, 01:14:33",
            art: "2 tracks, 01:14:33.jpg",
            url: "https://xoark.bandcamp.com/album/2-tracks-01-14-33",
            genre: XoarkGenre.IDM,
            duration: "01:14:33",
            rating: 2,
            type: XoarkAlbumType.Album,
            favorite: "21min01sec",
            listens: 1,
            series: XoarkSeries.Runtime,
        },
        {
            listened: "2026.08.07",
            released: "2024.11.16",
            title: "Tailflamed",
            art: "tailflamed.jpg",
            url: "https://xoark.bandcamp.com/album/tailflamed",
            genre: XoarkGenre.Breakcore,
            duration: "01:01:25",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "Antennak",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.08",
            released: "2024.11.16",
            title: "Nimnsk",
            art: "nimnsk.jpg",
            url: "https://xoark.bandcamp.com/album/nimnsk",
            genre: XoarkGenre.Breakcore,
            duration: "01:06:19",
            rating: 4,
            type: XoarkAlbumType.Album,
            favorite: "Macrhenkta",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.09",
            released: "2024.05.30",
            title: "Turphrwak",
            art: "turphrwak.jpg",
            url: "https://xoark.bandcamp.com/album/turphrwak",
            genre: XoarkGenre.IDM,
            duration: "00:47:53",
            rating: 3,
            type: XoarkAlbumType.Album,
            favorite: "06",
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.09",
            released: "2023.05.27",
            title: "Satellits: Placements",
            art: "satellits placements.jpg",
            url: "https://xoark.bandcamp.com/album/satellits-placements",
            genre: XoarkGenre.IDM,
            duration: "00:57:02",
            rating: 3,
            type: XoarkAlbumType.Album,
            favorite: "placement bar (0)",
            listens: 1,
            series: XoarkSeries.Satellits,
        },
        {
            listened: "2026.08.09",
            released: "2023.06.08",
            title: "Satellits: Descriptions",
            art: "satellits descriptions.jpg",
            url: "https://xoark.bandcamp.com/album/satellits-descriptions",
            genre: XoarkGenre.IDM,
            duration: "01:31:18",
            rating: 3,
            type: XoarkAlbumType.Album,
            favorite: "hshskhsk3",
            listens: 1,
            series: XoarkSeries.Satellits,
        },
        {
            listened: "2026.08.10",
            released: "2026.04.15",
            title: "Teacake Dress Empire",
            art: "teacake dress empire.jpg",
            url: "https://xoark.bandcamp.com/album/teacake-dress-empire",
            genre: XoarkGenre.Breakcore,
            duration: "00:59:04",
            rating: 3,
            type: XoarkAlbumType.Album,
            favorite: "Orkticxiyhi",
            favoriteNote: 'Has the "creature scuttling up stairs" sound at 0:27. And Chitose on the album cover which is a +.',
            listens: 1,
            series: XoarkSeries.None,
        },
        {
            listened: "2026.08.10",
            released: "2021.06.01",
            title: "P()~()..8",
            art: "p8.jpg",
            url: "https://xoark.bandcamp.com/album/p-8",
            genre: XoarkGenre.Breakcore,
            duration: "XX:XX:XX",
            rating: 3,
            type: XoarkAlbumType.Album,
            favorite: "",
            listens: 1,
            series: XoarkSeries.P,
        },
        {
            listened: "",
            released: "2023.01.28",
            title: "#d9eaf3",
            art: "d9eaf3.jpg",
            url: "https://xoark.bandcamp.com/album/d9eaf3",
            genre: XoarkGenre.Ambient,
            duration: "00:39:58",
            rating: 3,
            type: XoarkAlbumType.Journey,
            favorite: "",
            listens: 0,
            series: XoarkSeries.Hex,
        }
    ];
})();
