package database

// Walks a folder of album subfolders, reads FLAC metadata out of each track,
// and writes an .odin file containing one Album{} literal per album.

import "core:fmt"
import "core:os"
import "core:strings"
import "core:strconv"
import "core:path/filepath"
import "core:slice"
import "core:unicode"
import dt "core:time/datetime"

Type :: enum u8 {
	Album,
	EP,
	Split,
	VA,
	Journey,
	Single,
}

BANDCAMP_SUBDOMAIN :: "xoark"

main :: proc() {
	if len(os.args) < 2 {
		fmt.eprintln("usage: discography <artist-folder> [output.odin]")
		os.exit(1)
	}

	root := os.args[1]
	out_path := "albums_generated.odin"
	if len(os.args) >= 3 {
		out_path = os.args[2]
	}

	album_dirs, derr := list_subdirs(root)
	if derr != nil {
		fmt.eprintf("could not read %s: %v\n", root, derr)
		os.exit(1)
	}
	slice.sort(album_dirs[:])

	out_fd, oerr := os.open(out_path, os.O_WRONLY | os.O_CREATE | os.O_TRUNC)
	if oerr != nil {
		fmt.eprintf("could not create %s: %v\n", out_path, oerr)
		os.exit(1)
	}
	defer os.close(out_fd)

	fmt.fprint(out_fd, "package xoark_db\n\n")
	fmt.fprint(out_fd, "// Auto-generated by the discography scanner.\n")
	fmt.fprint(out_fd, "// Fill in fields marked TODO by hand: genre, type, series, rating,\n")
	fmt.fprint(out_fd, "// listened, favorite, comment, listens.\n\n")
	fmt.fprint(out_fd, "@rodata discography := []Album{\n")

	for name in album_dirs {
		album_path, _ := filepath.join([]string{root, name})
		process_album(album_path, name, out_fd)
	}

	fmt.fprintf(out_fd, "}\n")

	fmt.printf("wrote %s (%d albums)\n", out_path, len(album_dirs))
}

list_subdirs :: proc(root: string) -> (dirs: []string, err: os.Error) {
	fd, oerr := os.open(root)
	if oerr != nil {
		return nil, oerr
	}
	defer os.close(fd)

	infos, rerr := os.read_dir(fd, -1, context.allocator)
	if rerr != nil {
		return nil, rerr
	}

	names := make([dynamic]string)
	for info in infos {
		if info.type == .Directory && !strings.has_prefix(info.name, ".") {
			append(&names, info.name)
		}
	}
	return names[:], nil
}

collect_flac_files :: proc(dir_path: string) -> [dynamic]string {
	paths := make([dynamic]string)
	walk_for_flac(dir_path, &paths)
	return paths
}

walk_for_flac :: proc(dir_path: string, paths: ^[dynamic]string) {
	fd, oerr := os.open(dir_path)
	if oerr != nil {
		return
	}
	defer os.close(fd)

	infos, rerr := os.read_dir(fd, -1, context.allocator)
	if rerr != nil {
		return
	}

	for info in infos {
		full, _ := filepath.join([]string{dir_path, info.name})
		if info.type == .Directory {
			walk_for_flac(full, paths)
		} else if strings.has_suffix(strings.to_lower(info.name), ".flac") {
			append(paths, full)
		}
	}
}

process_album :: proc(album_path: string, folder_name: string, out_fd: ^os.File) {
	flac_paths := collect_flac_files(album_path)
	if len(flac_paths) == 0 {
		fmt.eprintf("WARNING: no .flac files found in %s\n", album_path)
	}
	slice.sort(flac_paths[:])

	tags := make(map[string]string)
	total_nanos: u64 = 0
	track_count := 0

	for path in flac_paths {
		info, ok := parse_flac(path)
		if !ok {
			fmt.eprintf("WARNING: could not parse %s\n", path)
			continue
		}
		track_count += 1

		if info.sample_rate > 0 {
			total_nanos += info.total_samples * 1_000_000_000 / u64(info.sample_rate)
		}

		for key, val in info.tags {
			if val == "" {
				continue
			}
			if _, exists := tags[key]; !exists {
				tags[key] = val
			}
		}
	}

	title, has_title := tags["ALBUM"]
	if !has_title || title == "" {
		fmt.eprintf("WARNING: %s has no ALBUM tag, falling back to folder name\n", album_path)
		title = folder_name
	}

	date_str := ""
	for key in ([]string{"DATE", "ORIGINALDATE", "RELEASEDATE", "YEAR"}) {
		if v, ok := tags[key]; ok && v != "" {
			date_str = v
			break
		}
	}
	if date_str == "" {
		fmt.eprintf("WARNING: %s has no DATE tag\n", album_path)
	}
	released := parse_date(date_str)
	duration := nanos_to_time(total_nanos)
	album_type := derive_type(track_count, total_nanos)

	slug := slugify(title)
	art := strings.concatenate({slug, ".jpg"})
	url := fmt.tprintf("https://%s.bandcamp.com/album/%s", BANDCAMP_SUBDOMAIN, slug)

	fmt.fprintf(out_fd, "\t{{\n")
	fmt.fprintf(out_fd, "\t\t// source folder: %s\n", folder_name)
	fmt.fprintf(out_fd, "\t\tgenre    = {{}},\n")
	fmt.fprintf(out_fd, "\t\ttype     = .%v,\n", album_type)
	fmt.fprintf(out_fd, "\t\tseries   = .None,\n")
	fmt.fprintf(out_fd, "\t\trating   = 0,\n")
	fmt.fprintf(out_fd, "\t\tlistened = {{}},\n")
	fmt.fprintf(out_fd, "\t\treleased = {{ year = %d, month = %d, day = %d }},\n", released.year, released.month, released.day)
	fmt.fprintf(out_fd, "\t\tduration = {{ hour = %d, minute = %d, second = %d, nano = %d }},\n", duration.hour, duration.minute, duration.second, duration.nano)
	fmt.fprintf(out_fd, "\t\ttitle    = %q,\n", title)
	fmt.fprintf(out_fd, "\t\tart      = %q,\n", art)
	fmt.fprintf(out_fd, "\t\turl      = %q,\n", url)
	fmt.fprintf(out_fd, "\t\tfavorite = \"\",\n")
	fmt.fprintf(out_fd, "\t\tcomment  = \"\",\n")
	fmt.fprintf(out_fd, "\t\tlistens  = 0,\n")
	fmt.fprintf(out_fd, "\t}},\n")
}

Flac_Info :: struct {
	sample_rate:   u32,
	total_samples: u64,
	tags:          map[string]string,
}

TOTAL_SAMPLES_MASK :: 0xF_FFFF_FFFF // 36 bits

read_u24be :: proc(b: []u8) -> u32 {
	return u32(b[0]) << 16 | u32(b[1]) << 8 | u32(b[2])
}

read_u32le :: proc(b: []u8) -> u32 {
	return u32(b[0]) | u32(b[1]) << 8 | u32(b[2]) << 16 | u32(b[3]) << 24
}

read_u64be :: proc(b: []u8) -> u64 {
	x: u64 = 0
	for i in 0 ..< 8 {
		x = x << 8 | u64(b[i])
	}
	return x
}

read_full :: proc(fd: ^os.File, buf: []u8) -> bool {
	total := 0
	for total < len(buf) {
		n, err := os.read(fd, buf[total:])
		if err != nil || n <= 0 {
			return false
		}
		total += n
	}
	return true
}

// Reads and discards n bytes from fd using a small fixed-size scratch
// buffer, so skipping past a huge PICTURE block (or the audio data itself)
// never allocates more than len(scratch) bytes.
skip_bytes :: proc(fd: ^os.File, n: int, scratch: []u8) {
	remaining := n
	for remaining > 0 {
		chunk := min(remaining, len(scratch))
		if !read_full(fd, scratch[:chunk]) {
			return
		}
		remaining -= chunk
	}
}

// Only reads FLAC metadata blocks (STREAMINFO + VORBIS_COMMENT), skipping
// everything else, including the audio data itself. This keeps memory use
// tiny and bounded regardless of how large the tracks are.
parse_flac :: proc(path: string) -> (info: Flac_Info, ok: bool) {
	fd, oerr := os.open(path)
	if oerr != nil {
		return {}, false
	}
	defer os.close(fd)

	magic: [4]u8
	if !read_full(fd, magic[:]) || string(magic[:]) != "fLaC" {
		return {}, false
	}

	info.tags = make(map[string]string)

	header_buf: [4]u8
	streaminfo_buf: [34]u8
	discard_buf: [65536]u8

	for {
		if !read_full(fd, header_buf[:]) {
			break
		}
		h := header_buf[0]
		is_last := h & 0x80 != 0
		block_type := h & 0x7F
		block_len := int(read_u24be(header_buf[1:4]))

		switch block_type {
		case 0: // STREAMINFO
			n := min(block_len, len(streaminfo_buf))
			if !read_full(fd, streaminfo_buf[:n]) {
				return info, true
			}
			if n >= 18 {
				packed := read_u64be(streaminfo_buf[10:18])
				info.sample_rate = u32(packed >> 44) & 0xFFFFF
				info.total_samples = packed & TOTAL_SAMPLES_MASK
			}
			skip_bytes(fd, block_len - n, discard_buf[:])
		case 4: // VORBIS_COMMENT
			comment_buf := make([]u8, block_len)
			if read_full(fd, comment_buf) {
				parse_vorbis_comment(comment_buf, &info.tags)
			}
			delete(comment_buf)
		case:
			// PADDING, APPLICATION, SEEKTABLE, CUESHEET, PICTURE, etc.
			skip_bytes(fd, block_len, discard_buf[:])
		}

		if is_last {
			break
		}
	}

	return info, true
}

parse_vorbis_comment :: proc(block: []u8, tags: ^map[string]string) {
	if len(block) < 4 {
		return
	}
	pos := 0
	vendor_len := int(read_u32le(block[pos : pos + 4]))
	pos += 4 + vendor_len
	if pos + 4 > len(block) {
		return
	}
	count := int(read_u32le(block[pos : pos + 4]))
	pos += 4

	for i in 0 ..< count {
		if pos + 4 > len(block) {
			break
		}
		entry_len := int(read_u32le(block[pos : pos + 4]))
		pos += 4
		if pos + entry_len > len(block) {
			break
		}
		entry := string(block[pos : pos + entry_len])
		pos += entry_len

		eq := strings.index_byte(entry, '=')
		if eq < 0 {
			continue
		}
		key := strings.to_upper(entry[:eq])
		val := strings.clone(entry[eq + 1:])
		tags[key] = val
	}
}

// ---------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------

// A single track under 15 minutes is a Single, a single track 15 minutes or
// longer is a Journey, anything with more than one track is a plain Album.
// (EP/Split/VA are never inferred — those need a human to set them.)
FIFTEEN_MINUTES_NANOS :: 15 * 60 * 1_000_000_000

derive_type :: proc(track_count: int, total_nanos: u64) -> Type {
	if track_count == 1 {
		if total_nanos < FIFTEEN_MINUTES_NANOS {
			return .Single
		}
		return .Journey
	}
	return .Album
}

parse_date :: proc(s: string) -> dt.Date {
	if s == "" {
		return dt.Date{}
	}
	parts := strings.split(s, "-")

	year: i64 = 0
	month: i8 = 1
	day: i8 = 1

	if len(parts) >= 1 {
		if v, ok := strconv.parse_i64(parts[0]); ok {
			year = v
		}
	}
	if len(parts) >= 2 {
		if v, ok := strconv.parse_int(parts[1]); ok {
			month = i8(v)
		}
	}
	if len(parts) >= 3 {
		if v, ok := strconv.parse_int(parts[2]); ok {
			day = i8(v)
		}
	}
	return dt.Date{year = year, month = month, day = day}
}

nanos_to_time :: proc(total_nanos: u64) -> dt.Time {
	ns := total_nanos
	hour := ns / 3_600_000_000_000
	ns %= 3_600_000_000_000
	minute := ns / 60_000_000_000
	ns %= 60_000_000_000
	second := ns / 1_000_000_000
	ns %= 1_000_000_000
	return dt.Time{hour = i8(hour), minute = i8(minute), second = i8(second), nano = i32(ns)}
}

// Lowercases, keeps letters/digits, collapses every other run of characters
// into a single dash, trims leading/trailing dashes.
// "[1701A961,xquri]" -> "1701a961-xquri"
slugify :: proc(s: string) -> string {
	b: strings.Builder
	strings.builder_init(&b)

	prev_sep := true
	for r in s {
		lr := unicode.to_lower(r)
		if unicode.is_letter(lr) || unicode.is_digit(lr) {
			strings.write_rune(&b, lr)
			prev_sep = false
		} else if !prev_sep {
			strings.write_rune(&b, '-')
			prev_sep = true
		}
	}

	return strings.trim_right(strings.to_string(b), "-")
}
